/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
/**
 * This sample demonstrates a simple skill built with the Amazon Alexa Skills
 * nodejs skill development kit.
 * This sample supports multiple lauguages. (en-US, en-GB, de-DE).
 * The Intent Schema, Custom Slots and Sample Utterances for this skill, as well
 * as testing instructions are located at https://github.com/alexa/skill-sample-nodejs-fact
 **/

'use strict';

const Alexa = require('alexa-sdk');

const APP_ID = undefined;  // TODO replace with your app ID (OPTIONAL).

const languageStrings = {
    'en': {
        translation: {
            FACTS: [
                "Women used to put drops of belladonna in the eyes to make their pupils dilate for reasons of fashion.",
                "The world may not be fair, but it’s a hell of a lot more fair then it’s ever been in history.",
                "Dutch police have trained eagles to take down drones.",
                "Eggplant Parmesan doesn’t actually require Parmesan cheese. It gets its name because the recipe is from Parma.",
                "Watching someone do a good deed inspires you to be better.",
                "Happiness results from being more of a taker than a giver. But meaningfulness results from being a more of a giver than a taker.",
                "Bank of America invented the credit card in Fresno.",
                "Self talk works better when you refer to yourself in 3rd person.",
                "Cooking unlocks more calories in your food.",
                "Different people get different amounts of calories from food. We think it has something to do with our gut bacteria.",
                "Cheaper weddings make for longer marriages.",
                "Generally, generalizations are too general.",
                "Every time someone writes a line of software, a job is lost.",
                "Originally, Dalí was going to play the Emperor in Dune.",
                "Maintaining self-esteem all the time is impossible unless you’re delusional. Be compassionate about your faults instead.",
                "Eagles mate in mid air.",
                "The can opener was invented almost 50 years before the can.",
                "You would only have to fold a piece of paper 42 times for it to reach the moon.",
                "From the time it was discovered until the time it was no longer a planet, Pluto never had the chance to fully orbit the sun once.",
                "Saudi Arabia imports camels from Australia.",
                "The founder of https://t.co/KSEbI6KW14 lost his girlfriend to a guy she met on https://t.co/KSEbI6KW14.",
                "More people are killed by vending machines than by sharks.",
                "The lighter was invented before the matchstick.",
                "The only country separating Finland and North Korea is Russia.",
                "In 2007, Iran arrested 14 squirrels on suspicion of espionage.",
                "Doctors who have been working 20 or 30 years make more mistakes than those who are just two or three years out of medical school.",
                "A sound is larger than a bay, deeper than a bight, and wider than a fjord",
                "There are also a lot of great artists and writers who _aren’t_ alcoholics and drug users.",
                "A good conversation is like a miniskirt; short enough to retain interest, but long enough to cover the subject.",
                "We are more polarized now than in any point in history.",
                "You’re not stupid, you’re just hanging around assholes who make you feel that way.",
                "You brain creates an image and double-checks with your eyes that what it imagines is correct. Not the other way around.",
                "What we think is reality is actualy just a 3D model we keep in our heads.",
                "Confucius, Buddha, and Pythagoras were contemporaries.",
                "Our bodies are just a provisional sketch of our total being.",
                "60% of all studies are incorrect.",
                "Not everything is art, but anything can be appreciated as art",
                "Everything comes in threes except for those things that don’t.",
                "Lipstick was outlawed in Britain in 1770 because it had the power to seduce men into marriage which was considered witchcraft.",
                "Statistically, 6 out of 7 dwarfs are not Happy.",
                "You are not dead to me until you exit the Krebs Cycle.",
                "We are all 25% banana. Genetically speaking.",
                "We all share about 25% of our genes with a banana. Or a cauliflower. Or any living thing really.",
                "William Howard Taft was America’s greatest president when measured by volume.",
                "Only about 10% of the world’s money is physical. The rest is digital.",
                "Sanity is about not expecting answers.",
                "The dropout rate of Alcoholics Anonymous is about 95%",
                "Flagellation is self punishment. Flatulation is punishment for others.",
                "Michelangelo use to forge art work and sell it.",
                "jacking off a turkey is called ‘securing a contribution.’ Apparently, it’s good seasonal work if you can get it.",
                "Permeated all around is is the 4th dimensional fabric known as space-time.",
                "The fastest way to a man’s heart is through his ribcage with a sharp knife. Not, as is commonly stated, his stomach.",
                "Michelangelo use to forge art work passing it off as ancient Roman sculpture.",
                "Based off the 9% mortality rate, the most dangerous job in the US is being the President. Next most dangerous is logging at 0.13%",
                "Some alligators put sticks on their noses to catch Egrets, the 1st known case of predators using lures based on seasonal behavior",
                "In the USA, forest growth has exceeded harvest since 1940 resulting in more trees now than at any time in the past 100 years.",
                "Technically all chaps are assless",
                "All arguments deep down are either about fear or respect.",
                "Belts were invented before pants, so technically your pants are holding your belt up, not the other way around.",
                "In America there is no greater crime than being poor.",
                "It takes even less muscles to shut the fuck up about the smile vs frown thing.",
                "It would take a little over 2 years to type all the words. By the time you were done, there would be more words to type.",
                "Mussolini did not make the trains fun on time. In fact they were almost always late.",
                "Stalin did not make the trains fun on time. In fact they were almost always late.",
                "The health care system that most people use in the US is prison.",
                "It is very hard for advertisers to establish if a marketing campaign actually got anyone to buy anything.",
                "Whales use clicks to distinguish themselves as members of their clicks.",
                "there are a quadrillion fish in the sea. About 50 trillion of them are a good catch.",
                "Advice is autobiography.",
                "it doesn’t count as a power nap unless it’s under 60 minutes.",
                "Statements that contain a random collection of vague buzzwords organized in a sentence with syntactic structure have meaning.",
                "A catalyst speeds up a process, but it would’ve reached it’s equilibrium anyway.",
                "The golden rule predates Christianity by at least a few thousand years.",
                "If you’re giving back to the community, you might’ve taken too much.",
                "Laughter is the cheesiest medicine.",
                "Richard Dawkins coined the term “meme” in 1976 to refer to a self-replicating “unit of cultural transmission”",
                "Kobe Bryant has the world record for missing more shots in professional basketball than any other player.",
                "The US has the fastest women in the world (at least when measured by foot races).",
                "If you dug straight through the earth anywhere in the US, you’d end up in the the ocean, not China.",
                "Many species are not even aware of us.",
                "Missing children were on milk cartons only 2 years. Of the 200 children, only 2 were found, only 1 because of the cartons.",
                "Nationalism is a dangerous idea that we need to overcome.",
                "The most translated words are “Thank you.” “How are you?” and “I love you.”",
                "The basketball was invented in 1891 for keeping football team in shape in the off season.",
                "If you brought the ozone layer down to the surface of the earth, atmospheric pressure would make it the thickness of two pennies.",
                "Energy is former mass.",
                "Martha was the last passenger pigeon. On 9/1/1914, as she died, her species went extinct.",
                "Cosmic rays zip through us at the rate of 3 to 4 times a second.",
                "Roman wine was so shitty that they had to cut it with anchovy juice just to make it taste better.",
                "Romans used urine as a mouth wash.",
                "The big bang was likely not a one-time event.",
                "To make a dollar go farther, you can bunch it up, put it in a slingshot, and shoot it off the roof of a very tall building.",
                "The only animal that kills more humans than us is mosquitos (people = 475,000/year, mosquitoes = 725,000/year).",
                "Iron is the end of energy. It’s the last element left from the death of a star.",
                "The part of you that holds memory is the youngest part of your body.",
                "94% of all matter is dark matter",
                "The telecommunications industry accounts for over 60% of space industry revenue.",
                "The entire GPS system only uses 32 satellites.",
                "Asking yourself why then “no. really. why?” 2 times finds the real answer. But go too far and you have an existential crisis.",
                "Ancient Romans used urine as mouthwash.",
                "Pumpkins are actually berries.",
                "Jenga blocks are slightly off shape from each other. Otherwise the game wouldn’t work.",
                "In a pinch, a spiderweb can be used as a bandaid.",
                "Men have a way of manipulating the women we don’t think we deserve but don’t want to lose.",
                "Studies suggest that being all touchy feely and hippie dippie makes you live longer.",
                "Leslie Nielsen is Liam Neeson’s father.",
                "½ of the all the humans who have ever existed have died of Malaria.",
                "Mother is a verb. It only turns into a noun over time.",
                "Everything important in life is an oxymoron.",
                "Lifelong learning not only adds years to your lie but life to your years.",
                "Companies are a fiction manifest by wizards that we call lawyers.",
                "Life is like math: all the leading zeros are insignificant.",
                "Pain is nature’s way of telling you that you’re doing something stupid.",
                "People would rather work with a lovable fool than a competent jerk.",
                "Self-delusion is the best protection against mediocrity.",
                "Only half of us are above average.",
                "Children are the RND department of the human race.",
                "Most of the information on the planet is stored in DNA.",
                "Sea level is the average of 19 years of sea levels.",
                "Things don’t get easier, you just get to know yourself better.",
                "What we experience as the present is actually about 80 milliseconds in the past.",
                "Time is measure of entropy. I one direction is chaos, in the other is order",
                "The Simplified Spelling Society is campaigning to remove the silent ‘w’.",
                "The 2nd law of thermodynamics states that it’s more fun to be messy than orderly.",
                "Self discipline is overrated and unreliable.",
                "Stress is a direct result of giving a fuck.",
                "Optimistic people are often late",
                "High-heel related emergency visits doubled between 2002 and 2012.",
                "Curiosity is the only technique for learning.",
                "People are 9 times more likely to die in a hospital on TV than they are in real life. Also, they are much more likely to be crazy.",
                "Phizer invent Viagra as heart medication, but discovered side effects when test subjects refused to give them back the drug.",
                "Robots are the new middle class.",
                "Making a decision is the act of picking out a box and then not thinking outside of it.",
                "The subjunctive mood makes everything possible.",
                "The universe is actually pretty ugly.",
                "FOMO is a negative valence state.",
                "Everyone is a little bit weird and nobody knows what they are doing.",
                "The secret to an active mind is to turn all the periods at the end of sentences into question marks.",
                "80% of elevator close buttons do not work. They are usually deactivated on purpose.",
                "Life is a buffet and not a fixed-price meal.",
                "Indigo is a fake color invented by Newton.",
                "In the David & Goliath story, Goliath was more of David.",
                "One of the hardest thing about being human is trying to figure how not to care too much, but to make sure not to care too little.",
                "If you care too much about what people think, then everybody starts lying to you.",
                "Hour per hour, Americans spend more time watching video than they do working.",
                "Economics is the mixing of the disciplines of statistics an astrology.",
                "Babies are really good at generalizing from small samples of data.",
                "Fire is essentially just tightly packed sunshine.",
                "80-85% of lightning strikes on people in the US happen to men.",
                "there are more arrowheads being flinted today by hobbyists than were ever made in prehistoric times.",
                "Vibrators were invented in the 1800 as a cure for “hysteria.”",
                "There is a BIG difference between a minor offense, and an offense with a minor. Or a miner.",
                "Boxer briefs are a sports bra for men’s junk.",
                "What used to be science fiction is now consumer electronics.",
                "There are more bacteria in your body than there are stars in the galaxy.",
                "Money is a pieces of paper fueled by a mythological story.",
                "Weird Twitter is apparently a thing.",
                "We are all immigrants when it comes to the realm of thought.",
                "As far as species go, humans are actually pretty new on the scene.",
                "The X in the X and Y axis is X because when the Spanish translated from Arabic, they couldn’t do the ‘sh’ sound.",
                "Spiderman kind of exists, but instead of a guy who shoots webs out of his wrist, it’s a goat that squirts silk out of her tits.",
                "Humans are a temporary container for their genes.",
                "70% of the stock market is algorithms talking to each other.",
                "The fact that we see time and distance as different things is only human prejudice. The only real difference is geometry.",
                "The debate is no longer about whether global warming exists. The debate now is “Holy shit, we’re fucked! What do we do now?”",
                "information and particles are considered the same thing in modern physics.",
                "Curiosity is the only technique for learning.",
                "The universe is actually pretty ugly if you really look at it.",
                "It is the subjunctive mood that makes everything possible.",
                "They’re both technically ‘metric’ systems; the Imperial system just uses a different metric.",
                "It takes 6 seconds of hugging to get the Oxytocin to start flowing",
                "Everyone has damage from childhood. If you don’t think you did, you just haven’t had enough therapy.",
                "The left brain / right brain dichotomy is bullshit.",
                "The cosmic background radiation was originally thought to be pigeon poop.",
                "At least two people invented the lightbulb before Edison.",
                "Rats didn’t spread the plague, it was actually giant Asian gerbils.",
                "The Universe is an outdated concept.",
                "Foreign military occupation of lands is the root cause of suicide attacks.",
                "Men are from Africa, women are from Africa (not Mars and Venus).",
                "My generation is the first one to make less than the the prior generation in over 5000 years.",
                "We need more women in tech. In fact, the survival of our species depends on it.",
                "Listerine is named after James Lister who invented antiseptic and trained Dr. Who in the art of medicine.",
                "Alan Turing was actually a pretty good athlete, had lots of friends, and didn’t do it alone. He was definitely quirky though.",
                "More women have been raped by dolphins than Bill Cosby.",
                "a person left naked in the cold at 0ºC would die in 20 minutes.",
                "93% of all people who have ever lived are dead. That’s 15 people for everyone alive today.",
                "Kokura was the town we were originally going bomb, but the weather was bad, so instead we hit Hiroshima. On this day in 1945.",
                "Individually, people are usually smarter than you think. Collectively, they’re as dumb as rocks.",
                "If asked Start Trek or Star Wars, the correct answer is Dr. Who.",
                "Monogamy was invented to protect a man’s property - namely his wife.",
                "If you want everything to be above average, you’re doing the math wrong.",
                "In a ‘he said, she said’ argument, the 'she said’ side is the one you should listen to.",
                "Because we blinking, none of us have ever seen a movie in its entirety.",
                "A thing is in fact identical to itself.",
                "Herb Caen coined “beatnik” in 1958 by adding the Russian suffix -nik after Sputnik to the Beat Generation in the SF Chronicle.",
                "We use way more than 10% of our brains.",
                "Surveillance is prevalent because it’s profitable.",
                "A diamond loses over 50% of its value as soon as you buy it.",
                "Hating yourself does not make you interesting.",
                "Sadness is a delusion.",
                "Normal is a lie told by politicians and jerks so they can sleep at night.",
                "Eyes are not needed to see. With echolocation, people can get about the resolution of a sighted person’s peripheral vision.",
                "We can sit around and drink a lot and talk about an idea, but we don’t know if it’s a good one or not until we do it.",
                "My favorite kind of factoid is bullshit that I generate myself. It tends to have a deeper truth than most other platitudes.",
                "If we DO find extraterrestrial life, it may conquer us.",
                "A lot of compassion comes down to just being there.",
                "Studies show that bees might be self medicating themselves with special plants when they are sick.",
                "Fortune cookies are Japanese, not Chinese.",
                "Rain can help blind people see because of the echoes created by the drops on their surroundings.",
                "It was only when we started owning things that we started going to war to protect those things.",
                "Life is all about finding other people to play with.",
                "If everybody cared about everybody else, no one would have to care about themselves.",
                "They only report the highly improbably stuff, so if it’s in the news you probably don’t have to worry about it.",
                "Most truths today are lies tomorrow.",
                "Snow White was the first thing ever storyboarded.",
                "Technically, Serotonin and Dopamine are the only two things you enjoy.",
                "The term ‘broadcasting’ was originally a farming term that referred to the distribution of seeds.",
                "We don’t see reality as it actually is. If we did, we wouldn’t be able to survive it.",
                "When (heterosexual) men learn about sex from other men, they are missing key primary source information.",
                "The Toaster Instagram filter is named after @kevinrose’s dog.",
                "our eyes have a resolution of about 130 Megapixels.",
                "Thomas Jefferson and John Adams both died on July 4, 1826.",
                "Our eyes have a resolution of about 130 Megapixels.",
                "John Adams believed July 2nd was the correct date to celebrate American Independence.",
                "Right now, 23:59:59 UTC, is now 23:59:60 because the earth is slowing down, we are all going to die, and time is a lie.",
                "The food chain is a euphemism for a murder/theft cycle.",
                "An opinion is a temporary understanding of facts frozen in a moment in time.",
                "90% of deforestation in the Rainforest is done illegally.",
                "Religion is a huge threat to spirituality.",
                "Actual memories only last for about 3 minutes before they become an invented reconstruction.",
                "The words “The American Dream” were coined by Fannie Mae in a marketing campaign 40 years ago to sell mortgages to slaves.",
                "The US government gets up to 50% of your paycheck and then 10-20% of that goes to kill people.",
                "Legendary Factoid-atician L.M. Boyd would’ve been 88 were he alive today",
                "At least 50% of what we know is wrong. Unfortunately, we never know which 50%",
                "80% of elevator close buttons do not work. They are usually deactivated on purpose.",
                "The secret to happiness is to be delusional.",
                "It is what it is, but sometimes in different lighting situations and from different angles, it can appear to be something else.",
                "Compassion pre-dates humanity. It can be thought of as a useful genetic trait to ensure kin selection to propagate a species.",
                "Castration increases longevity. But I wouldn’t advise it.",
                "Mass media is an aberration that’s only been around for a few generations and it won’t last much longer.",
                "You can re-carbonate champaign with a Sodastream. But I wouldn’t advise it.",
                "For the first time ever, more African’s are above the poverty line than are below it.",
                "There are about as many atoms in one grain of salt as there are grains of sand on all the beaches on Earth",
                "If you made a scale model of the Milky Way that was the size of the US, you would still need a microscope to see the sun.",
                "We’re not really a thing. We’re actually a grouping of a gazillion other things and just a tiny part of a much larger thing.",
                "A hiccup is a prehistoric remnant of when we were fish.",
                "A remarkable achievement is just a long series of unremarkable tasks viewed from far away.",
                "When bears hibernate, they reduce their heartbeat to 6 bmp, and they don’t shit.",
                "Bears love peanut butter marshmallows.",
                "Self is a painful illusion. Please find a constructive way to deal with it instead of drugs and/or crazy religious fanaticism.",
                "That the best way to get ahead is to slow down is demonstrated in both The Tortoise and the Hare parable and in orbital mechanics.",
                "A penny dropped of the Empire State building reaches terminal velocity of 50mph, which is not fast enough to kill you.",
                "If he calls you a tease, it just means that he’s an asshole who thinks you don’t have the right to say no.",
                "Self esteem has no correlation with wealth.",
                "The average pencil holds 25,000 words.",
                "It is only through critique that a finished work is realized.",
                "Lack of transparency has huge political advantages.",
                "All but one of the terrorist plots that were stopped by the CIA were actually first instigated by the CIA.",
                "Sandwiches are the “fuck it, we’ll do it live!” of the culinary world.",
                "Even plants have to make decisions. Though mostly they’re all about whether to store or create energy.",
                "We have all been aging since we were 2 years old.",
                "‘Impossible’ is a human invention.",
                "More fatal heart attacks happen at 9am on Monday morning that at any other time",
                "Lucy, a.k.a, AL 288-1 the oldest human found, was named after the Beatles song Lucy in the Sky With Diamonds",
                "Picasso thought he would be remembered as a writer who sometimes painted.",
                "The antibiotics we take are making mosquitoes stronger and live longer.",
                "Most statues are of corrupt men. A notable exception is the one of Henry Winkler in Wisconsin",
                "It turns out that the answer to why we exist might just be “meh” https://t.co/eXj3UdkmKq",
                "The most common form of clinical depression is called “atypical depression.”",
                "Dammit! @factofday went back in time and stole my idea before I had it!",
                "Twitter is lousy with them. Good thing this isn’t my day job. https://t.co/eq1UCWId17",
                "You only need your left hand to type Star Wars. #MayThe4thBeWithYou",
                "Luke Skywalker was originally going to be named Luke Starkiller. #MayThe4thBeWithYou",
                "It took Yoda 19.2 kilowatts of force to lift Luke’s the X-Wing out of the swamp. #MayThe4thBeWithYou",
                "In the Iliad, Homer describes the sea as ‘wine-dark’ because the color blue hadn’t been invented yet.",
                "It turns out that the answer to why we exist might be “meh” https://t.co/qVJDxCPa2v",
                "Making a false mayday call is a federal crime and can get you up to six years imprisonment and/or a fine of up to $250,000.",
                "Songs are really just very interesting things to be doing with the air.",
                "#Barcamp was the first hash tag",
                "When your DNA talks through your brain, it’s called instinct.",
                "Air raspberries would be a terrible name for farts.",
                "The number one thing in life that people crave is certainty. The 2nd most thing they crave is uncertainty.",
                "The grass is greener over on this side of the fence.",
                "A model is a useful lie you use in order to navigate reality",
                "Sometimes, 2 snowflakes are the same. In fact, there are only 35 different types of snowflakes.",
                "The Seven Years’ War, started by George Washington, was actually the first world war.",
                "Cognitive Behavioral Therapy states that thoughts don’t matter, it’s the reaction to the thoughts that matter. Freud disagreed.",
                "Ideas come slowly and with lots of collaboration.",
                "Coffee houses have been a great place for idea sex since the 1500s.",
                "Synthetic happiness is just as real and lasting as happiness earned.",
                "Stuff that happened 3 months ago has almost no effect on you happiness today.",
                "The human head actually weighs between 5 and 11 pounds, not necessarily 8.",
                "Taking your eyes off the road for 5 seconds is like travelling the length of a football field blind.",
                "Willpower is a finite resource. Use it wisely.",
                "Enlightenment is a direct result of seeing the world as it is.",
                "Depression is a direct result of seeing the world as it is.",
                "In a study where bees were fed cocaine, their little dances exaggerated to the others the amount of pollen they found.",
                "Fundamentalist religious belief is directly correlated to low IQ.",
                "The US Government has a picture of your dick. https://t.co/QtfWB3ievy",
                "Randomness clusters.",
                "To find out the answers to deep truths about the human condition, we would need to run some pretty unethical experiments.",
                "On average and as a whole, we have grown by 3 IQ points per year.",
                "The moon effects our sleep patterns even if we’re locked in a windowless room for months and can’t see the moon.",
                "420 was coined in 1971 at San Rafael High School when students would get stoned under the statue of Louis Pasteur at 4:20pm.",
                "420 was coined in 1971 at San Rafael High School when students would get stoned under the statue of Louis Pasteur at 4:20pm.",
                "Behind everyone’s success story is a least a few dozen failures.",
                "People from Moose Jaw Saskatchewan are known as Moose Javians.",
                "Italian, French, and Spanish are actually the exact same language, but with different accents.",
                "Our world is quite literally, by most metrics, getting more awesome all the time.",
                "Creativity is a process, not an event.",
                "The best way to fix the overpopulation problem is to increase the standard of living for women and girls.",
                "Creativity is applied imagination.",
                "Almost all assumptions are wrong, but they often work anyway.",
                "Play can be defined as being unpredictable, but safe.",
                "Cumulus are the friendliest of the clouds.",
                "Women aren’t crazy. People are crazy, and women just happen to be people",
                "We are all just merely a collection of chemical reactions.",
                "Believing that you are you are lucky and indebted to others will make you happier.",
                "You can add 56 years of life by donating your organs. Not your own life of course..",
                "Apple is america’s second favorite pie.",
                "Stuff doesn’t happen for a reason. Stuff happens, and then we assign reason to it.",
                "The stigma of Irish being drunkards goes back 2500 years.",
                "Reality doesn’t have to conform a narrative, so it’s story is free to be impossible and completely unreasonable.",
                "The Ides of March used to be the 1st full moon of the year until we started fucking with the calendar hundreds of years ago.",
                "Whales beach themselves because they get all freaked out by the sonar from military submarines.",
                "Pain is inevitable. Suffering is optional.",
                "You should probably just shut up and sit down.",
                "Our world is quite literally getting more awesome all the time.",
                "Certain understanding escapes meaningful linguistic understanding.",
                "Women are better suited to go to Mars than men. Which is ironic, because women are from Venus",
                "A study shows that owning a cat is detrimental to your mental health.",
                "The NSA warehouse in Bluffdale Utah stores over a Yottabyte. That’s the equivalent memory of 16 trillion personal computers.",
                "50% of what we know is wrong.",
                "Variability is measurable. Risk is not. Don’t control variability though, just measure it.",
                "Christopher Columbus was aware that the earth was round.",
                "The average flaccid penis is 3.61 inches long, and 5.16 inches erect.",
                "Humans have been graffiting on bathrooms for thousands of years",
                "Human struggle is the only interesting story to tell.",
                "Altruism predates religion.",
                "Any future prediction that is true won’t be believable. Any believable future prediction won’t come true.",
                "Being able to change your mind is probably the most important skill a person can have.",
                "Technically, there is only one way to die: not enough blood getting to your brain.",
                "I will now start tweeting at 5pm instead of 8pm because I read on the internet somewhere that it’s better this way for both of us.",
                "There is no path to happiness. Happiness IS the path.",
                "Everything is better with a little cheese. Or a lot of cheese.",
                "Girls who can run in heels should be feared.",
                "Martin Luther did a lot of his thinking on the toilet while taking a shit.",
                "Drug use is down worldwide.",
                "The reason our police have gotten so deadly is we keep buying them expensive toys so they feel like they need to use them.",
                "They found methane on Mars. I would’ve expected them to find it on Uranus.",
                "Girls who can run in heels should be feared.",
                "the only accident a Google self driving car has been in so far is when the driver took over and ran it into a Prius.",
                "Couples can sync their heart hate by staring into each other’s eyes.",
                "Hugs help you live longer.",
                "Cuddling helps alleviate headaches.",
                "Kissing helps lower cortisol, the stress hormone.",
                "Looking at a photo of a loved one can lessen physical pain.",
                "Love at first sight happens in less than 1/5th a second.",
                "Men fall more quickly in love than women.",
                "Falling in love can lower your serotonin levels so that you have the same amount as a person with OCD.",
                "Swans (usually) mate for life",
                "Oxytocin is boosted when you help someone, when you are helped, or even when you watch someone else being helped",
                "Every weapon is a sex toy if you hold it right.",
                "Love isn’t like pie in that you eat a piece and there’s less of it. It’s like pi: a ratio that is infinite and non-repeating.",
                "It’s already too late. Shit is going to start to get real, climatologically speaking.",
                "Malcolm X was assassinated 3 years before Martin Luther King.",
                "Gravity can be measured putting 13 tons of mercury next to a bit of copper. It’s roughly equivalent to weight of a human eyelash.",
                "Playing Tetris or Candy Crush after a traumatic event can dramatically reduce PTSD.",
                "In New York, for tax purposes, a burrito is a sandwich.",
                "There is a device called a penetrometer that measures ‘squishiness.’ Apparently, it is a scientific instrument, not a sex toy.",
                "-40º C is also -40º F",
                "Martin Luther wrote the first listicle that went viral.",
                "Love seems like a grand idea, but in reality it’s actually pretty gross and kinda smells funny.",
                "Almost every multi-billionaire alive today made their money by being born to the right person.",
                "The universe may not exist, but mathematics does.",
                "Over the years, Cosmo has recommended over 68,000 ways to please your man.",
                "There’s are lot of cool things named after dead physicists.",
                "Electrons don’t exist. Well, they sort of kinda exist in a statistically probable time and place.",
                "Other people elsewhere are different, nasty, and strange.",
                "The dollar is the de facto world currency, but we almost had one that could’ve been called the Orb, the Unicorn, or Bancor.",
                "The comma is the game changer of the punctuation world.",
                "Her name is Kitty White, not Hello Kitty.",
                "Pound for pound, beef is the most environmentally destructive food on the planet.",
                "Power-nap is an oxymoron.",
                "The water in San Francisco is so clean that when I you filter it taste worse.",
                "We are all trying to survive this horrible tragedy that we call life.",
                "Order does not exist, but it’s fun to imagine that it does.",
                "Native Americans learned scalping from the settlers.",
                "It takes longer to watch the Hobbit movies than it takes to read the Hobbit.",
                "Math might not exist.",
                "beer is a good antioxidant. The darker the more antioxidants.",
                "1 in every 100 Americans are in prison. That’s more prisoners than the whole of China has jailed.",
                "Electromagnetism is the kludge or two separate theories smushed into one",
                "If the earth were the size of an apple, then our atmosphere would be the size of the apple’s skin.",
                "As a species, pigeons do not get the respect they deserve.",
                "There are over 4800 songs about rainbows.",
                "75% of shit just doesn’t work out.",
                "Descartes had a fetish for cross-eyed women",
                "A burp is a wish your heart makes for more beer.",
                "Pablo Picasso’s stole his quote “bad artists copy, great artists steal” from a poet.",
                "Politics are not ruled by objective observation, but rather arbitrary belief and manipulations.",
                "It is not true that 93% of communication is non-verbal. The study just says facial expressions are more powerful than words.",
            ],
            SKILL_NAME: 'Factoids',
            GET_FACT_MESSAGE: "Factoid: ",
            HELP_MESSAGE: 'You can say tell me a factoid, or, you can say exit... What can I help you with?',
            HELP_REPROMPT: 'What can I help you with?',
            STOP_MESSAGE: 'Goodbye!',
        },
    },
};

const handlers = {
    'LaunchRequest': function () {
        this.emit('GetFact');
    },
    'GetNewFactIntent': function () {
        this.emit('GetFact');
    },
    'GetFact': function () {
        // Get a random factoid from the factoids list
        // Use this.t() to get corresponding language data
        const factArr = this.t('FACTS');
        const factIndex = Math.floor(Math.random() * factArr.length);
        const randomFact = factArr[factIndex];

        // Create speech output
        const speechOutput = this.t('GET_FACT_MESSAGE') + randomFact;
        this.emit(':tellWithCard', speechOutput, this.t('SKILL_NAME'), randomFact);
    },
    'AMAZON.HelpIntent': function () {
        const speechOutput = this.t('HELP_MESSAGE');
        const reprompt = this.t('HELP_MESSAGE');
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
};

exports.handler = function (event, context) {
    const alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    // To enable string internationalization (i18n) features, set a resources object.
    alexa.resources = languageStrings;
    alexa.registerHandlers(handlers);
    alexa.execute();
};
